config/routes.rb
Rails.application.routes.draw do
  get "/welcome", to: "welcome#index"
  resources :expenses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/dashboard", to: "dashboard#index"
  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    def index
        @expenses = Expense.all
    end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[ show edit update destroy ]

  # GET /expenses or /expenses.json
  def index
    @expenses = Expense.order(date: :asc)
    if params[:search_by_expense] && params[:search_by_expense] != ""
      @expenses = @expenses.where("expense like ?", 
      "#{params[:search_by_expense]}%")
    end
    if params[:search_by_date] && params[:search_by_date] != ""
      @expenses = @expenses.where("date like ?", 
      "#{params[:search_by_date]}%")
    end
  end

  # GET /expenses/1 or /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end


  # GET /expenses/1/edit
  def edit
  end
  

  # POST /expenses or /expenses.json
  def create
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to expense_url(@expense), notice: "Expense was successfully created." }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to expense_url(@expense), notice: "Expense was successfully updated." }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to expenses_url, notice: "Expense was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def expense_params
      params.require(:expense).permit(:expense, :amount, :obs, :date)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/index.html.erb
      <h2>Gastos</h2>
        <table class="table table-striped ">
          <thead>
            <tr>

              <th scope="col">expense</th>
              <th scope="col">amount</th>
              <th scope="col">details</th>
              <th scope="col">Occurence date</th>
            </tr>
          </thead>
          <tbody>
           <% @expenses.each do |e|%>
                <tr>
                <td> <%= link_to e.expense, e %> </td>
                <td> <%= e.amount %> </td>
                <td> <%= e.obs %> </td>
                <td> <%= e.date.strftime("%d/%m/%y") %> </td>
            <% end %>
                </tr>
          </tbody>
        </table>

app/views/expenses/_expense.html.erb
<div id="<%= dom_id expense %>">
  <p>
    <strong>Expense:</strong>
    <%= expense.expense %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= expense.amount %>
  </p>

  <p>
    <strong>Obs:</strong>
    <%= expense.obs %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= expense.date %>
  </p>

</div>

app/views/expenses/_form.html.erb
<%= form_with(model: expense) do |form| %>
  <% if expense.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :expense, style: "display: block" %>
    <%= form.text_field :expense %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.label :obs, style: "display: block" %>
    <%= form.text_area :obs %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render "form", expense: @expense %>

<br>

<div>
  <%= link_to "Show this expense", @expense %> |
  <%= link_to "Back to expenses", expenses_path %>
</div>

app/views/expenses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Expenses</h1>
<%= form_tag "/expenses", method: "GET" do %>
    <%= label_tag :search_by_expense %>
    <%= text_field_tag :search_by_expense, params[:search_by_expense] %>

    <%= submit_tag "Search"%>
<% end %>

<h3>Total spent  = <%=Expense.sum(:amount) %></h3>
<h3>Largest expense : <%= Expense.where(amount: Expense.maximum(:amount)).pick(:expense) %>, price = R$ <%=Expense.maximum(:amount) %> </h3>
<table table class = "table table-striped table-bordered">
  <thead> <th> id</th><th> Expense </th><th> Amount </th><th>Details</th><th>Occurence date</th> </thead>
    <tbody>
      <% @expenses.each do |e|%>
        <tr>
          <td> <%= link_to e.id, e %> </td>
          <td> <%= e.expense %> </td>
          <td> <%= e.amount %> </td>
          <td> <%= e.obs %> </td>
          <td> <%= e.date.strftime("%d/%m/%y") %> </td>
          <% end %>
        </tr>
        
    </tbody>

</table>
<p> </p>
<%= link_to "New expense", new_expense_path %>
<p> </p>
<%= link_to "Back", root_path %>

app/views/expenses/new.html.erb
<h1>New expense</h1>

<%= render "form", expense: @expense %>

<br>

<div>
  <%= link_to "Back to expenses", expenses_path %>
</div>

app/views/expenses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @expense %>

<div>
  <%= link_to "Edit this expense", edit_expense_path(@expense) %> |
  <%= link_to "Back to expenses", expenses_path %>

  <%= button_to "Destroy this expense", @expense, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
    <title>MoneyManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Monthly financial control!</h1>
<h3> Total spent : R$<%= Expense.sum(:amount)%></h3>
<h3>Largest expense : <%=Expense.where(amount: Expense.maximum(:amount)).pick(:expense)%>, amount =  R$<%=Expense.maximum(:amount) %> <h3>
<p> <p>
<%= link_to "New expense", new_expense_path %>
<p> <p>
<p> <%= link_to 'Month expenses', 'expenses#index' %> </p>